CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, email text UNIQUE NOT NULL, password_hash text NOT NULL,
 role text NOT NULL DEFAULT 'client' CHECK(role IN ('client','talent','reviewer','admin')), status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','SUSPENDED')),
 bio text, avatar_url text, skills text[] NOT NULL DEFAULT '{}', portfolio jsonb NOT NULL DEFAULT '[]', bank_code text, account_number text,
 paystack_recipient_code text, reviewer_score numeric, reviewer_level text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS webhook_events (event_key text PRIMARY KEY, provider text NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,ip text,user_agent text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS email_verifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,verified_at timestamptz);
CREATE TABLE IF NOT EXISTS password_resets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz);
CREATE TABLE IF NOT EXISTS jobs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),client_id uuid NOT NULL REFERENCES users(id),talent_id uuid REFERENCES users(id),title text NOT NULL,description text NOT NULL,budget numeric(14,2) NOT NULL CHECK(budget>0),currency text NOT NULL DEFAULT 'NGN',category text,deadline timestamptz,
 revision_count int NOT NULL DEFAULT 2 CHECK(revision_count>=0),revisions_used int NOT NULL DEFAULT 0,deliverables jsonb NOT NULL DEFAULT '[]',acceptance_criteria jsonb NOT NULL DEFAULT '[]',reference_urls jsonb NOT NULL DEFAULT '[]',
 status text NOT NULL DEFAULT 'OPEN',payment_status text NOT NULL DEFAULT 'UNPAID',payment_reference text,funded_at timestamptz,submitted_at timestamptz,approved_at timestamptz,review_deadline timestamptz,revision_reason text,submission_id uuid,qa jsonb,resolution jsonb,payout_reference text,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS proposals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,talent_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,message text NOT NULL DEFAULT '',quote numeric(14,2),status text NOT NULL DEFAULT 'PENDING',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(job_id,talent_id));
CREATE TABLE IF NOT EXISTS files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,submission_id uuid NOT NULL,original_name text NOT NULL,stored_name text NOT NULL UNIQUE,mime text,size bigint NOT NULL,sha256 text NOT NULL,preview_name text,access text NOT NULL DEFAULT 'PRIVATE_MASTER',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,reference text UNIQUE NOT NULL,amount numeric(14,2) NOT NULL,currency text NOT NULL DEFAULT 'NGN',provider text NOT NULL DEFAULT 'PAYSTACK',status text NOT NULL,paid_at timestamptz,provider_payload jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) UNIQUE,talent_id uuid NOT NULL REFERENCES users(id),amount numeric(14,2) NOT NULL,reference text UNIQUE,status text,provider_payload jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS disputes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,opened_by uuid NOT NULL REFERENCES users(id),reason text NOT NULL,evidence jsonb NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'OPEN',assigned_reviewer_id uuid REFERENCES users(id),decision jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reviewer_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,specialties jsonb NOT NULL DEFAULT '[]',experience text,portfolio jsonb NOT NULL DEFAULT '[]',references_json jsonb NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'PENDING',reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reviewer_tests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),application_id uuid UNIQUE NOT NULL REFERENCES reviewer_applications(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id),status text NOT NULL DEFAULT 'PENDING',score numeric,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,sender_id uuid NOT NULL REFERENCES users(id),body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,reviewer_id uuid NOT NULL REFERENCES users(id),reviewee_id uuid NOT NULL REFERENCES users(id),rating int NOT NULL CHECK(rating BETWEEN 1 AND 5),comment text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(job_id,reviewer_id));
CREATE INDEX IF NOT EXISTS reviews_reviewee_idx ON reviews(reviewee_id,created_at DESC);
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,type text NOT NULL,title text NOT NULL,body text NOT NULL,meta jsonb NOT NULL DEFAULT '{}',read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),action text NOT NULL,actor text,meta jsonb NOT NULL DEFAULT '{}',at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS settings (key text PRIMARY KEY,value jsonb NOT NULL);
INSERT INTO settings(key,value) VALUES('commission','12'),('reviewWindowHours','48'),('autoApproveHours','72') ON CONFLICT DO NOTHING;
CREATE INDEX IF NOT EXISTS webhook_events_created_idx ON webhook_events(created_at DESC);CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id);CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);CREATE INDEX IF NOT EXISTS jobs_client_idx ON jobs(client_id);CREATE INDEX IF NOT EXISTS jobs_talent_idx ON jobs(talent_id);CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs(status);CREATE INDEX IF NOT EXISTS jobs_category_idx ON jobs(category);CREATE INDEX IF NOT EXISTS proposals_job_idx ON proposals(job_id);CREATE INDEX IF NOT EXISTS files_job_idx ON files(job_id);CREATE INDEX IF NOT EXISTS payments_job_idx ON payments(job_id);CREATE INDEX IF NOT EXISTS disputes_job_idx ON disputes(job_id);CREATE INDEX IF NOT EXISTS messages_job_idx ON messages(job_id);CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS audit_at_idx ON audit(at DESC);
