import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import compression from 'compression';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { Pool } from 'pg';
import multer from 'multer';
import { z } from 'zod';
import { execFile } from 'child_process';
import nodemailer from 'nodemailer';
import { promisify } from 'util';
import { createServer } from 'http';
import { Server as SocketIOServer } from 'socket.io';

const exec = promisify(execFile);
const app = express();
const PORT = Number(process.env.PORT || 3000);
const ROOT = process.cwd();
const ORIG = path.join(ROOT, 'storage', 'originals');
const PREV = path.join(ROOT, 'storage', 'previews');
const TMP = path.join(ROOT, 'tmp');
for (const d of [ORIG, PREV, TMP]) fs.mkdirSync(d, { recursive: true });

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false, max: Number(process.env.DB_POOL_MAX || 20), idleTimeoutMillis: 30000, connectionTimeoutMillis: 10000 });
const q = (text, params = []) => pool.query(text, params);
const uid = () => crypto.randomUUID();
const sha = v => crypto.createHash('sha256').update(String(v)).digest('hex');
const now = () => new Date().toISOString();
const json = (v, fallback = {}) => v == null ? fallback : (typeof v === 'string' ? JSON.parse(v) : v);
const cleanUser = u => u && ({ id:u.id, name:u.name, email:u.email, role:u.role, status:u.status, bio:u.bio, avatarUrl:u.avatar_url, skills:u.skills, portfolio:u.portfolio, reviewerScore:u.reviewer_score, reviewerLevel:u.reviewer_level, emailVerified:u.email_verified, createdAt:u.created_at });
async function audit(action, actor, meta={}) { await q('INSERT INTO audit(action,actor,meta) VALUES($1,$2,$3)', [action, actor ? String(actor) : null, meta]); }
async function setting(key, fallback) { const r=await q('SELECT value FROM settings WHERE key=$1',[key]); return r.rowCount ? json(r.rows[0].value) : fallback; }
async function notify(userId, type, title, body, meta={}) { await q('INSERT INTO notifications(user_id,type,title,body,meta) VALUES($1,$2,$3,$4,$5)',[userId,type,title,body,meta]); }
const mailer = process.env.SMTP_HOST ? nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined}) : null;
async function sendMail(to,subject,text){if(!mailer)return false;await mailer.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to,subject,text});return true;}

app.set('trust proxy', process.env.TRUST_PROXY ? Number(process.env.TRUST_PROXY) : 1);
app.disable('x-powered-by');
app.use((req,res,next)=>{req.requestId=crypto.randomUUID();res.setHeader('X-Request-ID',req.requestId);next()});
const allowedOrigins=String(process.env.CORS_ORIGINS||process.env.APP_URL||'').split(',').map(x=>x.trim()).filter(Boolean);
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.length===0||allowedOrigins.includes(origin))return cb(null,true);return cb(new Error('Origin not allowed'))},credentials:false}));
app.use(helmet({ contentSecurityPolicy:false, crossOriginResourcePolicy:{policy:'cross-origin'} }));
app.use(compression());
app.use(express.json({limit:'2mb', verify:(req,res,buf)=>{req.rawBody=Buffer.from(buf)}}));
app.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');next()});
app.use(express.urlencoded({extended:true,limit:'2mb'}));
app.use(express.static(path.join(ROOT,'public')));
app.use('/api/', rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
app.use('/api/auth/', rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false}));

function token(req){return (req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();}
async function auth(req,res,next){try{const t=token(req);if(!t)return res.status(401).json({error:'Authentication required'});const r=await q(`SELECT u.*,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1`,[sha(t)]);const u=r.rows[0];if(!u||new Date(u.expires_at)<=new Date())return res.status(401).json({error:'Invalid or expired session'});if(u.status==='SUSPENDED')return res.status(403).json({error:'Account suspended'});req.user=u;req.tokenHash=sha(t);next()}catch(e){next(e)}}
const roles=(...rs)=>(req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({error:'Insufficient permissions'});
const requireVerified=(req,res,next)=>(req.user.email_verified||req.user.role==='admin')?next():res.status(403).json({error:'Please verify your email address before doing this. Check your inbox for a verification link.'});
const DISPOSABLE_DOMAINS=new Set(['mailinator.com','tempmail.com','temp-mail.org','guerrillamail.com','10minutemail.com','yopmail.com','trashmail.com','getnada.com','sharklasers.com','throwawaymail.com','fakeinbox.com','maildrop.cc','dispostable.com','mintemail.com','mohmal.com','moakt.com','emailondeck.com','tempinbox.com','mailnesia.com']);
function isDisposableEmail(email){const domain=String(email).split('@')[1]?.toLowerCase()||'';return DISPOSABLE_DOMAINS.has(domain)}
async function optionalAuth(req,res,next){try{const t=token(req);if(!t)return next();const r=await q(`SELECT u.*,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1`,[sha(t)]);const u=r.rows[0];if(u&&new Date(u.expires_at)>new Date()&&u.status!=='SUSPENDED')req.user=u;next()}catch(e){next()}}
const validate=(schema,where='body')=>(req,res,next)=>{try{req[where]=schema.parse(req[where]);next()}catch(e){next(e)}};
const idSchema=z.object({id:z.string().uuid()});
async function ensureAdmin(){const email=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),pw=String(process.env.ADMIN_PASSWORD||'');if(!email||!pw)return;const r=await q('SELECT * FROM users WHERE email=$1',[email]);if(!r.rowCount){const h=await bcrypt.hash(pw,12);const u=(await q("INSERT INTO users(name,email,password_hash,role,status) VALUES($1,$2,$3,'admin','ACTIVE') RETURNING id",['PRODILIVE Administrator',email,h])).rows[0];await audit('ADMIN_ACCOUNT_CREATED',u.id,{})}else if(r.rows[0].role!=='admin'||r.rows[0].status!=='ACTIVE')await q("UPDATE users SET role='admin',status='ACTIVE' WHERE id=$1",[r.rows[0].id])}
const registerSchema=z.object({name:z.string().trim().min(2).max(100),email:z.string().email().max(200),password:z.string().min(8).max(200),role:z.enum(['client','talent']).default('client')});

app.post('/api/auth/register',validate(registerSchema),async(req,res,next)=>{try{const x=req.body,email=x.email.toLowerCase();if(isDisposableEmail(email))return res.status(400).json({error:'Disposable/temporary email addresses are not allowed. Please use a real, permanent email.'});if((await q('SELECT 1 FROM users WHERE email=$1',[email])).rowCount)return res.status(409).json({error:'Email already registered'});const hashPw=await bcrypt.hash(x.password,12);const r=await q('INSERT INTO users(name,email,password_hash,role,email_verified) VALUES($1,$2,$3,$4,false) RETURNING *',[x.name,email,hashPw,x.role]);const u=r.rows[0],raw=crypto.randomBytes(32).toString('hex');await q("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[sha(raw),u.id]);const verifyRaw=crypto.randomBytes(32).toString('hex');await q("INSERT INTO email_verifications(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '24 hours')",[u.id,sha(verifyRaw)]);if(mailer)await sendMail(u.email,'Verify your PRODILIVE email',`${process.env.APP_URL||''}/api/auth/verify-email?token=${verifyRaw}`);await audit('USER_REGISTERED',u.id,{role:u.role});res.status(201).json({token:raw,user:cleanUser(u),emailVerificationRequired:true,mailerConfigured:Boolean(mailer)})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),pw=String(req.body.password||'');const u=(await q('SELECT * FROM users WHERE email=$1',[email])).rows[0];if(!u||!(await bcrypt.compare(pw,u.password_hash)))return res.status(401).json({error:'Invalid credentials'});if(u.status==='SUSPENDED')return res.status(403).json({error:'Account suspended'});const raw=crypto.randomBytes(32).toString('hex');await q("INSERT INTO sessions(token_hash,user_id,expires_at,ip,user_agent) VALUES($1,$2,now()+interval '30 days',$3,$4)",[sha(raw),u.id,req.ip,req.get('user-agent')||'']);await audit('LOGIN',u.id);res.json({token:raw,user:cleanUser(u)})}catch(e){next(e)}});
app.post('/api/auth/logout',auth,async(req,res,next)=>{try{await q('DELETE FROM sessions WHERE token_hash=$1',[req.tokenHash]);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/auth/verify-email',async(req,res,next)=>{try{const r=await q("SELECT * FROM email_verifications WHERE token_hash=$1 AND verified_at IS NULL AND expires_at>now()",[sha(String(req.query.token||''))]);if(!r.rowCount)return res.status(400).json({error:'Invalid or expired verification token'});await q('UPDATE email_verifications SET verified_at=now() WHERE id=$1',[r.rows[0].id]);await q('UPDATE users SET email_verified=true WHERE id=$1',[r.rows[0].user_id]);res.json({ok:true,message:'Email verified'})}catch(e){next(e)}});
app.post('/api/auth/resend-verification',auth,async(req,res,next)=>{try{if(req.user.email_verified)return res.json({ok:true,alreadyVerified:true});if(!mailer)return res.status(503).json({error:'Email sending is not configured on this server yet. Contact support.'});const verifyRaw=crypto.randomBytes(32).toString('hex');await q("INSERT INTO email_verifications(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '24 hours')",[req.user.id,sha(verifyRaw)]);await sendMail(req.user.email,'Verify your PRODILIVE email',`${process.env.APP_URL||''}/api/auth/verify-email?token=${verifyRaw}`);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/auth/forgot-password',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),u=(await q('SELECT id FROM users WHERE email=$1',[email])).rows[0];if(u){const raw=crypto.randomBytes(32).toString('hex');await q("INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '30 minutes')",[u.id,sha(raw)]);if(mailer)await sendMail(email,'Reset your PRODILIVE password',`${process.env.APP_URL||''}/reset-password?token=${raw}`);if(process.env.NODE_ENV!=='production')return res.json({ok:true,developmentToken:raw})}res.json({ok:true})}catch(e){next(e)}});
app.post('/api/auth/reset-password',async(req,res,next)=>{try{const raw=String(req.body.token||''),pw=String(req.body.password||'');if(pw.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});const r=await q("SELECT * FROM password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now()",[sha(raw)]);if(!r.rowCount)return res.status(400).json({error:'Invalid or expired reset token'});const x=r.rows[0];await q('UPDATE users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(pw,12),x.user_id]);await q('UPDATE password_resets SET used_at=now() WHERE id=$1',[x.id]);await q('DELETE FROM sessions WHERE user_id=$1',[x.user_id]);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/me',auth,(req,res)=>res.json({user:cleanUser(req.user)}));
app.put('/api/me',auth,async(req,res,next)=>{try{const name=req.body.name!=null?String(req.body.name).trim():req.user.name,bio=req.body.bio!=null?String(req.body.bio).slice(0,2000):req.user.bio;const skills=Array.isArray(req.body.skills)?req.body.skills.slice(0,50):req.user.skills||[],portfolio=Array.isArray(req.body.portfolio)?req.body.portfolio.slice(0,50):req.user.portfolio||[];const r=await q('UPDATE users SET name=$1,bio=$2,skills=$3,portfolio=$4 WHERE id=$5 RETURNING *',[name,bio,skills,portfolio,req.user.id]);await audit('PROFILE_UPDATED',req.user.id);res.json({user:cleanUser(r.rows[0])})}catch(e){next(e)}});

const jobCreate=z.object({title:z.string().trim().min(3).max(200),description:z.string().trim().min(10).max(10000),budget:z.coerce.number().positive().max(100000000),category:z.string().trim().max(100).optional(),deadline:z.string().datetime().optional(),revisionCount:z.coerce.number().int().min(0).max(20).default(2),deliverables:z.array(z.string().max(500)).max(50).default([]),acceptanceCriteria:z.array(z.string().max(500)).max(50).default([]),referenceUrls:z.array(z.string().url()).max(20).default([]),milestones:z.array(z.object({label:z.string().trim().min(1).max(200),amount:z.coerce.number().nonnegative().max(100000000)})).max(20).default([])});
const publicJob=j=>({...j,deliverables:json(j.deliverables,[]),acceptanceCriteria:json(j.acceptance_criteria,[]),referenceUrls:json(j.reference_urls,[]),milestones:json(j.milestones,[]),qa:json(j.qa,null),resolution:json(j.resolution,null)});
app.post('/api/jobs',auth,roles('client'),requireVerified,validate(jobCreate),async(req,res,next)=>{try{const x=req.body,instant=Boolean(req.body.instantClaim),r=await q(`INSERT INTO jobs(client_id,title,description,budget,category,deadline,revision_count,deliverables,acceptance_criteria,reference_urls,milestones,instant_claim) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,x.title,x.description,x.budget,x.category||null,x.deadline||null,x.revisionCount,x.deliverables,x.acceptanceCriteria,x.referenceUrls,x.milestones,instant]);await audit('JOB_CREATED',req.user.id,{jobId:r.rows[0].id});const pj=publicJob(r.rows[0]);io.emit('feed:job',{job:pj});res.status(201).json(pj)}catch(e){next(e)}});
app.post('/api/jobs/:id/claim',auth,roles('talent','reviewer'),requireVerified,async(req,res,next)=>{try{const r=await q("UPDATE jobs SET talent_id=$1,status='AWAITING_PAYMENT' WHERE id=$2 AND status='OPEN' AND instant_claim=true AND talent_id IS NULL RETURNING *",[req.user.id,req.params.id]);if(!r.rowCount)return res.status(409).json({error:'This job was already claimed by someone else.'});const j=r.rows[0];await audit('JOB_CLAIMED',req.user.id,{jobId:j.id});await notify(j.client_id,'JOB_CLAIMED','Your job was claimed',`${req.user.name} claimed “${j.title}” — fund it to begin.`,{jobId:j.id});io.emit('feed:jobClaimed',{jobId:j.id,talentName:req.user.name});res.json(publicJob(j))}catch(e){next(e)}});
app.get('/api/jobs',auth,async(req,res,next)=>{try{const status=req.query.status,category=req.query.category,search=String(req.query.search||'').trim();const p=[req.user.id],where=[`(j.client_id=$1 OR j.talent_id=$1 OR j.status='OPEN')`];if(status){p.push(status);where.push(`j.status=$${p.length}`)}if(category){p.push(category);where.push(`j.category=$${p.length}`)}if(search){p.push(`%${search}%`);where.push(`(j.title ILIKE $${p.length} OR j.description ILIKE $${p.length})`)}const r=await q(`SELECT j.*,c.name client_name,t.name talent_name FROM jobs j JOIN users c ON c.id=j.client_id LEFT JOIN users t ON t.id=j.talent_id WHERE ${where.join(' AND ')} ORDER BY j.created_at DESC LIMIT 200`,p);res.json({jobs:r.rows.map(x=>({...publicJob(x),clientName:x.client_name,talentName:x.talent_name}))})}catch(e){next(e)}});
app.get('/api/jobs/:id',auth,async(req,res,next)=>{try{const r=await q(`SELECT j.*,c.name client_name,c.email client_email,t.name talent_name FROM jobs j JOIN users c ON c.id=j.client_id LEFT JOIN users t ON t.id=j.talent_id WHERE j.id=$1`,[req.params.id]);if(!r.rowCount)return res.sendStatus(404);const j=r.rows[0];if(j.status!=='OPEN'&&![j.client_id,j.talent_id].includes(req.user.id)&&req.user.role!=='admin')return res.sendStatus(403);const files=(await q('SELECT id,original_name,mime,size,sha256,preview_name,created_at FROM files WHERE job_id=$1 ORDER BY created_at',[j.id])).rows;res.json({job:{...publicJob(j),clientName:j.client_name,talentName:j.talent_name},files})}catch(e){next(e)}});
app.post('/api/jobs/:id/assign',auth,roles('client'),async(req,res,next)=>{try{const client=await q('SELECT * FROM jobs WHERE id=$1 AND client_id=$2',[req.params.id,req.user.id]);if(!client.rowCount||client.rows[0].status!=='OPEN')return res.status(400).json({error:'Job unavailable'});const t=(await q("SELECT id FROM users WHERE id=$1 AND role IN ('talent','reviewer') AND status='ACTIVE'",[req.body.talentId])).rows[0];if(!t)return res.status(404).json({error:'Talent not found'});const r=await q("UPDATE jobs SET talent_id=$1,status='AWAITING_PAYMENT' WHERE id=$2 AND client_id=$3 AND status='OPEN' RETURNING *",[t.id,req.params.id,req.user.id]);if(!r.rowCount)return res.status(409).json({error:'Job changed; try again'});await audit('TALENT_ASSIGNED',req.user.id,{jobId:req.params.id,talentId:t.id});await notify(t.id,'JOB_ASSIGNED','New job assigned',`You have been assigned “${r.rows[0].title}”.`,{jobId:req.params.id});res.json(publicJob(r.rows[0]))}catch(e){next(e)}});
app.post('/api/jobs/:id/apply',auth,roles('talent'),requireVerified,async(req,res,next)=>{try{const r=await q('SELECT * FROM jobs WHERE id=$1 AND status=$2',[req.params.id,'OPEN']);if(!r.rowCount)return res.status(404).json({error:'Open job not found'});if((await q('SELECT 1 FROM proposals WHERE job_id=$1 AND talent_id=$2',[req.params.id,req.user.id])).rowCount)return res.status(409).json({error:'Already applied'});const p=await q('INSERT INTO proposals(job_id,talent_id,message,quote,status) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.params.id,req.user.id,String(req.body.message||'').slice(0,3000),req.body.quote==null?null:Number(req.body.quote),'PENDING']);await notify(r.rows[0].client_id,'PROPOSAL','New talent proposal',`${req.user.name} applied to “${r.rows[0].title}”`,{jobId:req.params.id,proposalId:p.rows[0].id});res.status(201).json(p.rows[0])}catch(e){next(e)}});
app.get('/api/jobs/:id/proposals',auth,async(req,res,next)=>{try{const j=(await q('SELECT * FROM jobs WHERE id=$1',[req.params.id])).rows[0];if(!j|| (j.client_id!==req.user.id&&req.user.role!=='admin'))return res.sendStatus(403);const r=await q('SELECT p.*,u.name,u.email,u.skills,u.portfolio,u.bio FROM proposals p JOIN users u ON u.id=p.talent_id WHERE p.job_id=$1 ORDER BY p.created_at DESC',[req.params.id]);res.json({proposals:r.rows.map(x=>({...x,skills:json(x.skills,[]),portfolio:json(x.portfolio,[])}))})}catch(e){next(e)}});
app.post('/api/proposals/:id/accept',auth,roles('client'),async(req,res,next)=>{try{const r=await q(`SELECT p.*,j.client_id,j.status FROM proposals p JOIN jobs j ON j.id=p.job_id WHERE p.id=$1 AND j.client_id=$2`,[req.params.id,req.user.id]);if(!r.rowCount||r.rows[0].status!=='OPEN')return res.status(400).json({error:'Proposal unavailable'});const p=r.rows[0];await q("UPDATE proposals SET status='ACCEPTED' WHERE id=$1",[p.id]);const j=await q("UPDATE jobs SET talent_id=$1,status='AWAITING_PAYMENT' WHERE id=$2 RETURNING *",[p.talent_id,p.job_id]);await q("UPDATE proposals SET status='REJECTED' WHERE job_id=$1 AND id<>$2 AND status='PENDING'",[p.job_id,p.id]);await notify(p.talent_id,'JOB_ASSIGNED','Proposal accepted',`Your proposal for “${j.rows[0].title}” was accepted.`,{jobId:p.job_id});res.json(publicJob(j.rows[0]))}catch(e){next(e)}});

async function paystack(endpoint,method='GET',body){if(!process.env.PAYSTACK_SECRET_KEY)throw Error('PAYSTACK_SECRET_KEY is not configured');const r=await fetch('https://api.paystack.co'+endpoint,{method,headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok||j.status===false)throw Error(j.message||'Paystack request failed');return j.data}
app.post('/api/payments/initialize',auth,roles('client'),requireVerified,async(req,res,next)=>{try{const j=(await q('SELECT * FROM jobs WHERE id=$1 AND client_id=$2',[req.body.jobId,req.user.id])).rows[0];if(!j)return res.sendStatus(404);if(j.status!=='AWAITING_PAYMENT')return res.status(400).json({error:'Job is not awaiting funding'});if(Number(j.budget)<=0)return res.status(400).json({error:'Invalid budget'});const reference=`PRODILIVE_${j.id}_${Date.now()}`;const p=await paystack('/transaction/initialize','POST',{email:req.user.email,amount:Math.round(Number(j.budget)*100),currency:'NGN',reference,metadata:{jobId:j.id,type:'MARKETPLACE_JOB'}});await q('INSERT INTO payments(job_id,reference,amount,status,currency,provider) VALUES($1,$2,$3,$4,$5,$6)',[j.id,reference,j.budget,'INITIALIZED','NGN','PAYSTACK']);await q("UPDATE jobs SET payment_status='PAYMENT_INITIALIZED',payment_reference=$1 WHERE id=$2",[reference,j.id]);await audit('PAYMENT_INITIALIZED',req.user.id,{jobId:j.id,reference});res.json({authorization_url:p.authorization_url,access_code:p.access_code,reference})}catch(e){next(e)}});
app.get('/api/payments/verify/:reference',auth,roles('client'),async(req,res,next)=>{try{const p=(await q('SELECT p.*,j.client_id,j.title FROM payments p JOIN jobs j ON j.id=p.job_id WHERE p.reference=$1 AND j.client_id=$2',[req.params.reference,req.user.id])).rows[0];if(!p)return res.sendStatus(404);const remote=await paystack('/transaction/verify/'+encodeURIComponent(p.reference));if(remote.status==='success'&&p.status!=='HELD'){const expectedKobo=Math.round(Number(p.amount)*100);if(Number(remote.amount)!==expectedKobo||String(remote.currency||'NGN')!=='NGN')return res.status(400).json({error:'Payment amount or currency mismatch'});await q("UPDATE payments SET status='HELD',paid_at=now(),provider_payload=$1 WHERE id=$2",[remote,p.id]);await q("UPDATE jobs SET payment_status='HELD',status='IN_PROGRESS',funded_at=now() WHERE id=$1",[p.job_id]);await audit('PAYMENT_VERIFIED','PAYSTACK',{jobId:p.job_id,reference:p.reference})}res.json({status:remote.status,reference:p.reference})}catch(e){next(e)}});
app.post('/api/paystack/webhook',async(req,res)=>{try{const sig=String(req.headers['x-paystack-signature']||''),expected=crypto.createHmac('sha512',process.env.PAYSTACK_SECRET_KEY||'').update(req.rawBody||'').digest('hex');if(!sig||sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return res.sendStatus(401);const eventKey=sha(req.rawBody||'');const claimed=await q("INSERT INTO webhook_events(event_key,provider,event_type,payload) VALUES($1,'PAYSTACK',$2,$3) ON CONFLICT(event_key) DO NOTHING RETURNING event_key",[eventKey,String(req.body?.event||'UNKNOWN'),req.body||{}]);if(!claimed.rowCount)return res.sendStatus(200);res.sendStatus(200);const event=req.body;if(event.event==='charge.success'){const ref=event.data.reference;const r=await q('SELECT * FROM payments WHERE reference=$1',[ref]);if(r.rowCount&&r.rows[0].status!=='HELD'){const p=r.rows[0];if(Number(event.data.amount)!==Math.round(Number(p.amount)*100)||String(event.data.currency||'NGN')!=='NGN'){await audit('PAYMENT_WEBHOOK_REJECTED','PAYSTACK',{reference:ref,reason:'amount_or_currency_mismatch'});return}await q("UPDATE payments SET status='HELD',paid_at=now(),provider_payload=$1 WHERE id=$2",[event.data,p.id]);const j=(await q("UPDATE jobs SET payment_status='HELD',status='IN_PROGRESS',funded_at=now() WHERE id=$1 RETURNING *",[p.job_id])).rows[0];if(j){await audit('PAYMENT_CONFIRMED_HELD','PAYSTACK',{jobId:j.id,reference:ref});if(j.talent_id)await notify(j.talent_id,'PAYMENT_HELD','Job funded',`“${j.title}” is funded and ready for production.`,{jobId:j.id})}}}else if(['refund.processed','refund.failed','refund.pending'].includes(event.event)){const ref=event.data.transaction_reference||event.data.reference;const status=event.event==='refund.processed'?'REFUNDED':event.event==='refund.failed'?'REFUND_FAILED':'REFUND_PROCESSING';const p=(await q('UPDATE payments SET status=$1,provider_payload=$2 WHERE reference=$3 RETURNING *',[status,event.data,ref])).rows[0];if(p){await audit('REFUND_WEBHOOK','PAYSTACK',{jobId:p.job_id,reference:ref,status});if(status==='REFUNDED')await q("UPDATE jobs SET payment_status='REFUNDED',status='CANCELLED' WHERE id=$1",[p.job_id])}}else if(['transfer.success','transfer.failed','transfer.reversed'].includes(event.event)){const ref=event.data.reference;const status=event.event==='transfer.success'?'SUCCESS':event.event==='transfer.failed'?'FAILED':'REVERSED';const p=(await q('UPDATE payouts SET status=$1,provider_payload=$2 WHERE reference=$3 RETURNING *',[status,event.data,ref])).rows[0];if(p){if(status==='SUCCESS'){await q("UPDATE jobs SET payment_status='RELEASED',status='RELEASED' WHERE id=$1 AND payment_status='RELEASE_PENDING'",[p.job_id])}else{await q("UPDATE jobs SET payment_status='RELEASE_PENDING',status='APPROVED' WHERE id=$1 AND status='RELEASED'",[p.job_id])}await audit('PAYOUT_WEBHOOK', 'PAYSTACK',{jobId:p.job_id,reference:ref,status})}}}catch(e){console.error('Paystack webhook:',e)}});
const ALLOWED_UPLOAD_MIMES=new Set(String(process.env.ALLOWED_UPLOAD_MIMES||'audio/mpeg,audio/wav,audio/x-wav,audio/mp4,audio/aac,audio/flac,audio/ogg,application/zip,application/pdf,image/png,image/jpeg').split(',').map(x=>x.trim().toLowerCase()));
const upload=multer({dest:TMP,limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||500)*1024*1024,files:10},fileFilter:(req,file,cb)=>ALLOWED_UPLOAD_MIMES.has(String(file.mimetype).toLowerCase())?cb(null,true):cb(Object.assign(new Error('Unsupported file type'),{code:'LIMIT_UNEXPECTED_FILE'}))});
async function makePreview(input,out,mime){if(!/^audio\//.test(mime))return false;try{await exec('ffmpeg',['-y','-i',input,'-stream_loop','-1','-f','lavfi','-i','sine=frequency=1200:duration=0.15,apad=whole_dur=3','-filter_complex','[0:a]volume=0.55,afade=t=in:st=0:d=0.5,afade=t=out:st=0:d=0.5[main];[1:a]volume=0.15[tone];[main][tone]amix=inputs=2:duration=first:dropout_transition=0','-vn','-c:a','aac','-b:a','128k','-metadata','comment=PRODILIVE PROTECTED PREVIEW - NOT LICENSED FOR USE',out],{timeout:120000});return true}catch(e){console.error('preview',e.message);return false}}
app.post('/api/jobs/:id/deliver',auth,roles('talent','reviewer'),upload.array('files',10),async(req,res,next)=>{try{const j=(await q('SELECT * FROM jobs WHERE id=$1 AND talent_id=$2',[req.params.id,req.user.id])).rows[0];if(!j)return res.sendStatus(404);if(!['IN_PROGRESS','REVISION_REQUESTED'].includes(j.status))return res.status(400).json({error:'Job is not accepting delivery'});if(!req.files?.length)return res.status(400).json({error:'At least one file is required'});const submission=uid(),items=[];for(const f of req.files){const safe=path.basename(f.originalname).replace(/[^a-zA-Z0-9._-]/g,'_');const stored=`${submission}_${uid()}_${safe}`,target=path.join(ORIG,stored);fs.renameSync(f.path,target);const digest=crypto.createHash('sha256').update(fs.readFileSync(target)).digest('hex');const r=await q(`INSERT INTO files(job_id,submission_id,original_name,stored_name,mime,size,sha256) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[j.id,submission,f.originalname,stored,f.mimetype,f.size,digest]);const file=r.rows[0],pp=path.join(PREV,`${file.id}.m4a`);if(await makePreview(target,pp,f.mimetype)){await q('UPDATE files SET preview_name=$1 WHERE id=$2',[path.basename(pp),file.id]);file.preview_name=path.basename(pp)}items.push(file)}const rw=Number(await setting('reviewWindowHours',48));await q("UPDATE jobs SET submission_id=$1,status='QA_PENDING',submitted_at=now(),review_deadline=now()+($2::text || ' hours')::interval,qa=$3 WHERE id=$4",[submission,String(rw),JSON.stringify({technical:'PENDING',human:'NOT_REQUIRED',notes:[]}),j.id]);await audit('DELIVERY_SUBMITTED',req.user.id,{jobId:j.id,submissionId:submission,fileCount:items.length});await notify(j.client_id,'DELIVERY','Delivery submitted',`A delivery for “${j.title}” is ready for review.`,{jobId:j.id});res.json({jobId:j.id,submissionId:submission,files:items.map(f=>({id:f.id,name:f.original_name,previewUrl:`/api/files/${f.id}/preview`,downloadUrl:`/api/files/${f.id}/master`}))})}catch(e){for(const f of req.files||[])if(fs.existsSync(f.path))fs.unlinkSync(f.path);next(e)}});
async function fileFor(fid){return (await q('SELECT f.*,j.client_id,j.talent_id,j.status,j.payment_status FROM files f JOIN jobs j ON j.id=f.job_id WHERE f.id=$1',[fid])).rows[0]}
app.get('/api/files/:id/preview',auth,async(req,res,next)=>{try{const f=await fileFor(req.params.id);if(!f||![f.client_id,f.talent_id].map(String).includes(String(req.user.id))&&req.user.role!=='admin')return res.sendStatus(404);if(!f.preview_name)return res.status(404).json({error:'Preview unavailable for this file'});const p=path.join(PREV,f.preview_name);if(!fs.existsSync(p))return res.sendStatus(404);res.set('Cache-Control','private,no-store,max-age=0');res.set('X-Prodilive-Preview','protected');res.sendFile(p)}catch(e){next(e)}});
app.get('/api/files/:id/master',auth,async(req,res,next)=>{try{const f=await fileFor(req.params.id);if(!f||String(f.client_id)!==String(req.user.id)&&req.user.role!=='admin')return res.status(403).json({error:'Master unavailable'});if(!['RELEASED','RESOLVED_RELEASE'].includes(f.status)||f.payment_status!=='RELEASED')return res.status(403).json({error:'Master is locked until payment is released'});const p=path.join(ORIG,f.stored_name);if(!fs.existsSync(p))return res.sendStatus(404);await audit('MASTER_DOWNLOADED',req.user.id,{jobId:f.job_id,fileId:f.id});res.download(p,f.original_name)}catch(e){next(e)}});

app.post('/api/jobs/:id/qa',auth,roles('admin','reviewer'),async(req,res,next)=>{try{const j=(await q('SELECT * FROM jobs WHERE id=$1',[req.params.id])).rows[0];if(!j)return res.sendStatus(404);if(!['QA_PENDING','IN_PROGRESS'].includes(j.status))return res.status(400).json({error:'Job is not awaiting QA'});const result=req.body.technical==='FAIL'?'FAIL':'PASS',notes=Array.isArray(req.body.notes)?req.body.notes.slice(0,50):[],rw=Number(await setting('reviewWindowHours',48));const qa={technical:result,human:'NOT_REQUIRED',notes,reviewerId:req.user.id,checkedAt:now()};await q("UPDATE jobs SET qa=$1,status=$2,review_deadline=now()+($3::text || ' hours')::interval WHERE id=$4",[JSON.stringify(qa),result==='PASS'?'CLIENT_REVIEW':'REVISION_REQUESTED',String(rw),j.id]);await audit('TECHNICAL_QA_COMPLETED',req.user.id,{jobId:j.id,result});await notify(j.client_id,'QA_COMPLETE','Quality check complete',result==='PASS'?`“${j.title}” passed technical QA and is ready for your review.`:`“${j.title}” needs a revision.`,{jobId:j.id});res.json({ok:true,status:result==='PASS'?'CLIENT_REVIEW':'REVISION_REQUESTED',qa})}catch(e){next(e)}});
app.post('/api/jobs/:id/approve',auth,roles('client'),async(req,res,next)=>{try{const r=await q("UPDATE jobs SET status='APPROVED',payment_status='RELEASE_PENDING',approved_at=now() WHERE id=$1 AND client_id=$2 AND status='CLIENT_REVIEW' RETURNING *",[req.params.id,req.user.id]);if(!r.rowCount)return res.status(400).json({error:'Job is not awaiting approval'});await audit('DELIVERY_APPROVED',req.user.id,{jobId:req.params.id});await notify(r.rows[0].talent_id,'APPROVED','Delivery approved',`“${r.rows[0].title}” was approved. Payout is now pending release.`,{jobId:r.rows[0].id});res.json(publicJob(r.rows[0]))}catch(e){next(e)}});
app.post('/api/jobs/:id/revision',auth,roles('client'),async(req,res,next)=>{try{const j=(await q('SELECT * FROM jobs WHERE id=$1 AND client_id=$2',[req.params.id,req.user.id])).rows[0];if(!j)return res.sendStatus(404);if(!['CLIENT_REVIEW','QA_PENDING'].includes(j.status))return res.status(400).json({error:'Job is not in review'});if(j.revisions_used>=j.revision_count)return res.status(400).json({error:'Included revisions exhausted'});const r=await q("UPDATE jobs SET revisions_used=revisions_used+1,status='REVISION_REQUESTED',revision_reason=$1 WHERE id=$2 RETURNING *",[String(req.body.reason||'').slice(0,3000),j.id]);await audit('REVISION_REQUESTED',req.user.id,{jobId:j.id,revision:r.rows[0].revisions_used});await notify(j.talent_id,'REVISION','Revision requested',`A revision was requested for “${j.title}”.`,{jobId:j.id});res.json(publicJob(r.rows[0]))}catch(e){next(e)}});

app.post('/api/jobs/:id/dispute',auth,async(req,res,next)=>{try{const j=(await q('SELECT * FROM jobs WHERE id=$1',[req.params.id])).rows[0];if(!j||![j.client_id,j.talent_id].includes(req.user.id))return res.sendStatus(404);if(['RELEASED','CANCELLED'].includes(j.status))return res.status(400).json({error:'Job already closed'});if((await q("SELECT 1 FROM disputes WHERE job_id=$1 AND status IN ('OPEN','ASSIGNED')",[j.id])).rowCount)return res.status(409).json({error:'An active dispute already exists'});const r=await q("INSERT INTO disputes(job_id,opened_by,reason,evidence) VALUES($1,$2,$3,$4) RETURNING *",[j.id,req.user.id,String(req.body.reason||'').slice(0,5000),Array.isArray(req.body.evidence)?req.body.evidence:[]]);await q("UPDATE jobs SET status='DISPUTED',payment_status='FROZEN' WHERE id=$1",[j.id]);await audit('DISPUTE_OPENED',req.user.id,{jobId:j.id,disputeId:r.rows[0].id});res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.get('/api/disputes',auth,async(req,res,next)=>{try{const r=await q(`SELECT d.*,j.title,j.budget,j.client_id,j.talent_id FROM disputes d JOIN jobs j ON j.id=d.job_id WHERE $1='admin' OR d.opened_by=$2 OR d.assigned_reviewer_id=$2 ORDER BY d.created_at DESC`,[req.user.role,req.user.id]);res.json({disputes:r.rows})}catch(e){next(e)}});
app.post('/api/admin/disputes/:id/assign',auth,roles('admin'),async(req,res,next)=>{try{const r=await q("UPDATE disputes SET assigned_reviewer_id=$1,status='ASSIGNED' WHERE id=$2 AND EXISTS(SELECT 1 FROM users u WHERE u.id=$1 AND u.role IN ('reviewer','admin') AND u.status='ACTIVE') RETURNING *",[req.body.reviewerId,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Dispute or reviewer not found'});res.json(r.rows[0])}catch(e){next(e)}});

app.post('/api/reviewer/apply',auth,requireVerified,async(req,res,next)=>{try{if((await q("SELECT 1 FROM reviewer_applications WHERE user_id=$1 AND status IN ('PENDING','QUALIFICATION','APPROVED')",[req.user.id])).rowCount)return res.status(409).json({error:'Application already active'});const r=await q('INSERT INTO reviewer_applications(user_id,specialties,experience,portfolio,references_json) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.user.id,JSON.stringify(req.body.specialties||[]),String(req.body.experience||''),JSON.stringify(req.body.portfolio||[]),JSON.stringify(req.body.references||[])]);await audit('REVIEWER_APPLICATION_SUBMITTED',req.user.id,{applicationId:r.rows[0].id});res.status(201).json(r.rows[0])}catch(e){next(e)}});

app.put('/api/me/payout-profile',auth,roles('talent','reviewer'),async(req,res,next)=>{try{if(!req.body.bankCode||!/^\d{3}$/.test(String(req.body.bankCode))||!/^[0-9]{10}$/.test(String(req.body.accountNumber)))return res.status(400).json({error:'Valid Nigerian bank code and 10-digit account number required'});await q('UPDATE users SET bank_code=$1,account_number=$2,paystack_recipient_code=NULL WHERE id=$3',[String(req.body.bankCode),String(req.body.accountNumber),req.user.id]);await audit('PAYOUT_PROFILE_UPDATED',req.user.id);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/admin/payments/:jobId/refund',auth,roles('admin'),async(req,res,next)=>{try{const p=(await q(`SELECT p.*,j.title,j.status,j.client_id FROM payments p JOIN jobs j ON j.id=p.job_id WHERE p.job_id=$1 ORDER BY p.created_at DESC LIMIT 1`,[req.params.jobId])).rows[0];if(!p)return res.status(404).json({error:'Payment not found'});if(!['HELD','RELEASE_PENDING','FROZEN'].includes(p.status))return res.status(400).json({error:'Payment is not refundable in its current state'});const amount=Math.round(Number(p.amount)*100);const refund=await paystack('/refund','POST',{transaction:p.reference,amount});await q("UPDATE payments SET status='REFUND_PROCESSING',provider_payload=$1 WHERE id=$2",[refund,p.id]);await q("UPDATE jobs SET payment_status='REFUND_PENDING',status='DISPUTED' WHERE id=$1",[p.job_id]);await audit('REFUND_INITIATED',req.user.id,{jobId:p.job_id,reference:p.reference,amount:amount/100});res.json({ok:true,refund})}catch(e){next(e)}});

app.post('/api/admin/payouts/:jobId/release',auth,roles('admin'),async(req,res,next)=>{try{const c=await q('SELECT commission FROM settings WHERE key=$1',['commission']);const commission=Number(c.rowCount?json(c.rows[0].value):12);const j=(await q('SELECT * FROM jobs WHERE id=$1',[req.params.jobId])).rows[0];if(!j||!j.talent_id)return res.status(404).json({error:'Job/talent not found'});if(j.payment_status!=='RELEASE_PENDING')return res.status(400).json({error:'Payment not ready for release'});const talent=(await q('SELECT * FROM users WHERE id=$1',[j.talent_id])).rows[0];if(!talent.bank_code||!talent.account_number)return res.status(400).json({error:'Talent payout details missing'});if(!talent.paystack_recipient_code){const recipient=await paystack('/transferrecipient','POST',{type:'nuban',name:talent.name,account_number:talent.account_number,bank_code:talent.bank_code,currency:'NGN'});await q('UPDATE users SET paystack_recipient_code=$1 WHERE id=$2',[recipient.recipient_code,talent.id]);talent.paystack_recipient_code=recipient.recipient_code}const percent=Number(j.resolution?.talentPercent??100),amount=Math.round(Number(j.budget)*percent/100*(1-commission/100)*100);if(amount<=0)return res.status(400).json({error:'Payout amount is zero'});const reference=`PRODILIVE_PAYOUT_${j.id}`;const existing=await q('SELECT * FROM payouts WHERE job_id=$1',[j.id]);let created;if(existing.rowCount){const old=existing.rows[0];if(['PROCESSING','PENDING','SUCCESS'].includes(String(old.status).toUpperCase()))return res.json({job:publicJob(j),payout:old});created=(await q("UPDATE payouts SET talent_id=$1,amount=$2,reference=$3,status='PROCESSING',provider_payload=$4 WHERE job_id=$5 RETURNING *",[talent.id,amount/100,`${reference}_${Date.now()}`,JSON.stringify({requestedBy:req.user.id,retry:true}),j.id])).rows[0]}else{created=(await q("INSERT INTO payouts(job_id,talent_id,amount,reference,status,provider_payload) VALUES($1,$2,$3,$4,'PROCESSING',$5) RETURNING *",[j.id,talent.id,amount/100,reference,JSON.stringify({requestedBy:req.user.id})])).rows[0]}let transfer;try{transfer=await paystack('/transfer','POST',{source:'balance',amount,recipient:talent.paystack_recipient_code,reason:`PRODILIVE payout ${j.id}`,reference:created.reference});await q('UPDATE payouts SET status=$1,provider_payload=$2 WHERE id=$3',[transfer.status||'PROCESSING',transfer,created.id]);}catch(err){await q("UPDATE payouts SET status='FAILED',provider_payload=$1 WHERE id=$2",[JSON.stringify({error:err.message}),created.id]);throw err}const p=(await q('SELECT * FROM payouts WHERE id=$1',[created.id])).rows[0];await q("UPDATE jobs SET payout_reference=$1 WHERE id=$2",[transfer.reference,j.id]);await audit('PAYOUT_INITIATED',req.user.id,{jobId:j.id,amount:amount/100,reference:transfer.reference});await notify(talent.id,'PAYOUT','Payout initiated',`Payout for “${j.title}” has been initiated.`,{jobId:j.id});res.json({jobId:j.id,payout:p})}catch(e){next(e)}});

app.get('/api/notifications',auth,async(req,res,next)=>{try{const r=await q('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id]);res.json({notifications:r.rows})}catch(e){next(e)}});
app.post('/api/notifications/:id/read',auth,async(req,res,next)=>{try{await q('UPDATE notifications SET read_at=now() WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/messages/:jobId',auth,async(req,res,next)=>{try{const j=(await q('SELECT client_id,talent_id FROM jobs WHERE id=$1',[req.params.jobId])).rows[0];if(!j||![j.client_id,j.talent_id].includes(req.user.id)&&req.user.role!=='admin')return res.sendStatus(403);const r=await q('SELECT m.*,u.name sender_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.job_id=$1 ORDER BY m.created_at ASC LIMIT 500',[req.params.jobId]);res.json({messages:r.rows})}catch(e){next(e)}});
app.post('/api/messages/:jobId',auth,requireVerified,async(req,res,next)=>{try{const j=(await q('SELECT client_id,talent_id,title FROM jobs WHERE id=$1',[req.params.jobId])).rows[0];if(!j||![j.client_id,j.talent_id].includes(req.user.id))return res.sendStatus(403);const body=String(req.body.body||'').trim();if(!body||body.length>5000)return res.status(400).json({error:'Message must be 1-5000 characters'});const r=await q('INSERT INTO messages(job_id,sender_id,body) VALUES($1,$2,$3) RETURNING *',[req.params.jobId,req.user.id,body]);const other=req.user.id===j.client_id?j.talent_id:j.client_id;if(other)await notify(other,'MESSAGE',`New message about “${j.title}”`,body.slice(0,200),{jobId:j.id,messageId:r.rows[0].id});res.status(201).json(r.rows[0])}catch(e){next(e)}});

app.get('/api/talents',auth,async(req,res,next)=>{try{const s=String(req.query.search||'').trim();const p=['talent','ACTIVE'];let extra='';if(s){p.push(`%${s}%`);extra=`AND (u.name ILIKE $3 OR u.bio ILIKE $3 OR array_to_string(u.skills,',') ILIKE $3)`}const r=await q(`SELECT id,name,bio,skills,portfolio,reviewer_score,reviewer_level,created_at FROM users u WHERE role=$1 AND status=$2 ${extra} ORDER BY created_at DESC LIMIT 100`,p);res.json({talents:r.rows.map(x=>({...x,skills:json(x.skills,[]),portfolio:json(x.portfolio,[])}))})}catch(e){next(e)}});

const serviceCreate=z.object({title:z.string().trim().min(3).max(200),description:z.string().trim().max(3000).default(''),price:z.coerce.number().positive().max(100000000),deliveryDays:z.coerce.number().int().min(1).max(365).default(5),revisionCount:z.coerce.number().int().min(0).max(20).default(2)});
app.post('/api/services',auth,roles('talent'),validate(serviceCreate),async(req,res,next)=>{try{const x=req.body,r=await q('INSERT INTO services(talent_id,title,description,price,delivery_days,revision_count) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.user.id,x.title,x.description,x.price,x.deliveryDays,x.revisionCount]);await audit('SERVICE_CREATED',req.user.id,{serviceId:r.rows[0].id});res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.get('/api/services/mine',auth,roles('talent'),async(req,res,next)=>{try{const r=await q('SELECT * FROM services WHERE talent_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json({services:r.rows})}catch(e){next(e)}});
app.put('/api/services/:id',auth,roles('talent'),async(req,res,next)=>{try{const active=req.body.active!=null?Boolean(req.body.active):undefined;const s=(await q('SELECT * FROM services WHERE id=$1 AND talent_id=$2',[req.params.id,req.user.id])).rows[0];if(!s)return res.sendStatus(404);const title=req.body.title!=null?String(req.body.title).trim().slice(0,200):s.title,description=req.body.description!=null?String(req.body.description).slice(0,3000):s.description,price=req.body.price!=null?Number(req.body.price):s.price;const r=await q('UPDATE services SET title=$1,description=$2,price=$3,active=$4 WHERE id=$5 RETURNING *',[title,description,price>0?price:s.price,active==null?s.active:active,s.id]);res.json(r.rows[0])}catch(e){next(e)}});
app.get('/api/talents/:id/services',auth,async(req,res,next)=>{try{const r=await q('SELECT * FROM services WHERE talent_id=$1 AND active=true ORDER BY created_at DESC',[req.params.id]);res.json({services:r.rows})}catch(e){next(e)}});
app.post('/api/services/:id/order',auth,roles('client'),requireVerified,async(req,res,next)=>{try{const s=(await q('SELECT * FROM services WHERE id=$1 AND active=true',[req.params.id])).rows[0];if(!s)return res.status(404).json({error:'Service not found or no longer available'});const talent=(await q("SELECT id FROM users WHERE id=$1 AND role='talent' AND status='ACTIVE'",[s.talent_id])).rows[0];if(!talent)return res.status(404).json({error:'Provider unavailable'});const j=await q(`INSERT INTO jobs(client_id,talent_id,title,description,budget,category,revision_count,status) VALUES($1,$2,$3,$4,$5,$6,$7,'AWAITING_PAYMENT') RETURNING *`,[req.user.id,s.talent_id,s.title,s.description||s.title,s.price,'Service',s.revision_count]);await audit('SERVICE_ORDERED',req.user.id,{serviceId:s.id,jobId:j.rows[0].id});await notify(s.talent_id,'SERVICE_ORDER','New service order',`${req.user.name} ordered “${s.title}”.`,{jobId:j.rows[0].id});res.status(201).json(publicJob(j.rows[0]))}catch(e){next(e)}});

/* ============================ MARKETPLACE: PRODUCTS (beats/tracks/templates) ============================ */
const publicProduct = p => ({ id:p.id, sellerId:p.seller_id, sellerName:p.seller_name, title:p.title, description:p.description, category:p.category, price:Number(p.price), licenseTerms:p.license_terms, hasPreview:Boolean(p.preview_file_name), coverImageUrl:p.cover_image_url, active:p.active, salesCount:p.sales_count, createdAt:p.created_at });

app.get('/api/products',async(req,res,next)=>{try{const cat=req.query.category?String(req.query.category).toUpperCase():null;const search=req.query.q?`%${String(req.query.q).slice(0,100)}%`:null;const params=[];let where="p.active=true";if(cat){params.push(cat);where+=` AND p.category=$${params.length}`}if(search){params.push(search);where+=` AND (p.title ILIKE $${params.length} OR p.description ILIKE $${params.length})`}const r=await q(`SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE ${where} ORDER BY p.created_at DESC LIMIT 100`,params);res.json({products:r.rows.map(publicProduct)})}catch(e){next(e)}});

app.get('/api/products/mine',auth,requireVerified,async(req,res,next)=>{try{const r=await q('SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE p.seller_id=$1 ORDER BY p.created_at DESC',[req.user.id]);res.json({products:r.rows.map(publicProduct)})}catch(e){next(e)}});

app.get('/api/products/:id',optionalAuth,async(req,res,next)=>{try{const r=await q('SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE p.id=$1',[req.params.id]);if(!r.rowCount)return res.sendStatus(404);const p=r.rows[0];let owned=false;if(req.user)owned=Boolean((await q("SELECT 1 FROM product_orders WHERE product_id=$1 AND buyer_id=$2 AND status='PAID'",[p.id,req.user.id])).rowCount)||String(p.seller_id)===String(req.user.id);res.json({product:publicProduct(p),owned})}catch(e){next(e)}});

app.post('/api/products',auth,requireVerified,upload.fields([{name:'master',maxCount:1},{name:'cover',maxCount:1}]),async(req,res,next)=>{try{
  const title=String(req.body.title||'').trim().slice(0,200),description=String(req.body.description||'').slice(0,3000),category=String(req.body.category||'BEAT').toUpperCase(),price=Number(req.body.price);
  if(!title||!price||price<0)return res.status(400).json({error:'Title and a valid price are required'});
  if(!['BEAT','TRACK','TEMPLATE','SAMPLE_PACK','OTHER'].includes(category))return res.status(400).json({error:'Invalid category'});
  const masterFile=req.files?.master?.[0];
  if(!masterFile)return res.status(400).json({error:'A master file upload is required'});
  const safe=path.basename(masterFile.originalname).replace(/[^a-zA-Z0-9._-]/g,'_'),stored=`prod_${uid()}_${safe}`,target=path.join(ORIG,stored);
  fs.renameSync(masterFile.path,target);
  let previewName=null;
  if(/^audio\//.test(masterFile.mimetype)){const pp=path.join(PREV,`prod_${uid()}.m4a`);if(await makePreview(target,pp,masterFile.mimetype))previewName=path.basename(pp)}
  const r=await q(`INSERT INTO products(seller_id,title,description,category,price,master_file_name,master_original_name,master_mime,preview_file_name,license_terms) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.user.id,title,description,category,price,stored,masterFile.originalname,masterFile.mimetype,previewName,String(req.body.licenseTerms||'Standard non-exclusive license').slice(0,2000)]);
  await audit('PRODUCT_LISTED',req.user.id,{productId:r.rows[0].id});
  const full={...r.rows[0],seller_name:req.user.name};
  io.emit('feed:product',{product:publicProduct(full)});
  res.status(201).json(publicProduct(full));
}catch(e){for(const arr of Object.values(req.files||{}))for(const f of arr)if(fs.existsSync(f.path))fs.unlinkSync(f.path);next(e)}});

app.put('/api/products/:id',auth,requireVerified,async(req,res,next)=>{try{const p=(await q('SELECT * FROM products WHERE id=$1 AND seller_id=$2',[req.params.id,req.user.id])).rows[0];if(!p)return res.sendStatus(404);const active=req.body.active!=null?Boolean(req.body.active):p.active;const price=req.body.price!=null?Number(req.body.price):p.price;const r=await q('UPDATE products SET active=$1,price=$2 WHERE id=$3 RETURNING *',[active,price>0?price:p.price,p.id]);res.json(publicProduct({...r.rows[0],seller_name:req.user.name}))}catch(e){next(e)}});

app.get('/api/products/:id/preview',optionalAuth,async(req,res,next)=>{try{const p=(await q('SELECT * FROM products WHERE id=$1',[req.params.id])).rows[0];if(!p||!p.preview_file_name)return res.sendStatus(404);const f=path.join(PREV,p.preview_file_name);if(!fs.existsSync(f))return res.sendStatus(404);res.set('Cache-Control','private,no-store,max-age=0');res.sendFile(f)}catch(e){next(e)}});

app.get('/api/products/:id/download',auth,async(req,res,next)=>{try{const p=(await q('SELECT * FROM products WHERE id=$1',[req.params.id])).rows[0];if(!p)return res.sendStatus(404);const owns=String(p.seller_id)===String(req.user.id)||Boolean((await q("SELECT 1 FROM product_orders WHERE product_id=$1 AND buyer_id=$2 AND status='PAID'",[p.id,req.user.id])).rowCount)||req.user.role==='admin';if(!owns)return res.status(403).json({error:'Purchase required to download'});const f=path.join(ORIG,p.master_file_name);if(!fs.existsSync(f))return res.sendStatus(404);await audit('PRODUCT_DOWNLOADED',req.user.id,{productId:p.id});res.download(f,p.master_original_name)}catch(e){next(e)}});

app.post('/api/products/:id/purchase',auth,requireVerified,async(req,res,next)=>{try{const p=(await q('SELECT * FROM products WHERE id=$1 AND active=true',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Product not found or no longer available'});if(String(p.seller_id)===String(req.user.id))return res.status(400).json({error:'You cannot purchase your own listing'});if(Number(p.price)<=0)return res.status(400).json({error:'Invalid price'});const reference=`PRODILIVE_PRODUCT_${p.id}_${Date.now()}`;const pay=await paystack('/transaction/initialize','POST',{email:req.user.email,amount:Math.round(Number(p.price)*100),currency:'NGN',reference,metadata:{productId:p.id,type:'MARKETPLACE_PRODUCT'}});await q('INSERT INTO product_orders(product_id,buyer_id,seller_id,amount,reference,status) VALUES($1,$2,$3,$4,$5,$6)',[p.id,req.user.id,p.seller_id,p.price,reference,'INITIALIZED']);await audit('PRODUCT_PURCHASE_INITIALIZED',req.user.id,{productId:p.id,reference});res.json({authorization_url:pay.authorization_url,access_code:pay.access_code,reference})}catch(e){next(e)}});

app.get('/api/product-orders/verify/:reference',auth,async(req,res,next)=>{try{const o=(await q('SELECT * FROM product_orders WHERE reference=$1 AND buyer_id=$2',[req.params.reference,req.user.id])).rows[0];if(!o)return res.sendStatus(404);if(o.status==='PAID')return res.json({status:'success',reference:o.reference});const remote=await paystack('/transaction/verify/'+encodeURIComponent(o.reference));if(remote.status==='success'){const expectedKobo=Math.round(Number(o.amount)*100);if(Number(remote.amount)!==expectedKobo||String(remote.currency||'NGN')!=='NGN')return res.status(400).json({error:'Payment amount or currency mismatch'});await q("UPDATE product_orders SET status='PAID',paid_at=now(),provider_payload=$1 WHERE id=$2",[remote,o.id]);await q('UPDATE products SET sales_count=sales_count+1 WHERE id=$1',[o.product_id]);await notify(o.seller_id,'PRODUCT_SALE','You made a sale!',`Your listing sold for ₦${o.amount}.`,{productId:o.product_id});await audit('PRODUCT_PURCHASE_VERIFIED','PAYSTACK',{productId:o.product_id,reference:o.reference})}res.json({status:remote.status,reference:o.reference})}catch(e){next(e)}});

app.get('/api/products/mine/orders',auth,requireVerified,async(req,res,next)=>{try{const r=await q(`SELECT o.*,p.title FROM product_orders o JOIN products p ON p.id=o.product_id WHERE o.buyer_id=$1 AND o.status='PAID' ORDER BY o.paid_at DESC`,[req.user.id]);res.json({orders:r.rows})}catch(e){next(e)}});

app.post('/api/jobs/:id/review',auth,roles('client'),async(req,res,next)=>{try{const rating=Number(req.body.rating),comment=String(req.body.comment||'').trim().slice(0,3000);if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({error:'Rating must be an integer from 1 to 5'});const j=(await q('SELECT * FROM jobs WHERE id=$1 AND client_id=$2',[req.params.id,req.user.id])).rows[0];if(!j||j.status!=='RELEASED')return res.status(400).json({error:'Job must be released before review'});if((await q('SELECT 1 FROM reviews WHERE job_id=$1 AND reviewer_id=$2',[j.id,req.user.id])).rowCount)return res.status(409).json({error:'Review already submitted'});const r=await q('INSERT INTO reviews(job_id,reviewer_id,reviewee_id,rating,comment) VALUES($1,$2,$3,$4,$5) RETURNING *',[j.id,req.user.id,j.talent_id,rating,comment]);await audit('REVIEW_SUBMITTED',req.user.id,{jobId:j.id,reviewId:r.rows[0].id,rating});res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.get('/api/talents/:id/reviews',auth,async(req,res,next)=>{try{const r=await q('SELECT r.*,u.name reviewer_name FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.reviewee_id=$1 ORDER BY r.created_at DESC LIMIT 100',[req.params.id]);res.json({reviews:r.rows})}catch(e){next(e)}});

app.get('/api/admin/overview',auth,roles('admin'),async(req,res,next)=>{try{const [u,j,p,d]=await Promise.all([q('SELECT count(*)::int n FROM users'),q('SELECT count(*)::int n FROM jobs'),q("SELECT COALESCE(sum(amount),0)::numeric total FROM payments WHERE status IN ('HELD','RELEASED')"),q("SELECT count(*)::int n FROM disputes WHERE status IN ('OPEN','ASSIGNED')")]);res.json({users:u.rows[0].n,jobs:j.rows[0].n,revenue:Number(p.rows[0].total),openDisputes:d.rows[0].n})}catch(e){next(e)}});
app.get('/api/admin/users',auth,roles('admin'),async(req,res,next)=>{try{const r=await q('SELECT * FROM users ORDER BY created_at DESC LIMIT 1000');res.json({users:r.rows.map(cleanUser)})}catch(e){next(e)}});
app.put('/api/admin/users/:id/role',auth,roles('admin'),async(req,res,next)=>{try{if(!['client','talent','reviewer','admin'].includes(req.body.role))return res.status(400).json({error:'Invalid role'});if(req.params.id===req.user.id&&req.body.role!=='admin')return res.status(400).json({error:'Cannot remove own admin access'});const r=await q('UPDATE users SET role=$1 WHERE id=$2 RETURNING *',[req.body.role,req.params.id]);if(!r.rowCount)return res.sendStatus(404);await audit('ADMIN_CHANGED_USER_ROLE',req.user.id,{userId:req.params.id,newRole:req.body.role});res.json({user:cleanUser(r.rows[0])})}catch(e){next(e)}});
app.post('/api/admin/users/:id/suspend',auth,roles('admin'),async(req,res,next)=>{try{if(req.params.id===req.user.id)return res.status(400).json({error:'Cannot suspend yourself'});const r=await q("UPDATE users SET status='SUSPENDED' WHERE id=$1 RETURNING *",[req.params.id]);if(!r.rowCount)return res.sendStatus(404);await q('DELETE FROM sessions WHERE user_id=$1',[req.params.id]);await audit('ADMIN_SUSPENDED_USER',req.user.id,{userId:req.params.id});res.json({user:cleanUser(r.rows[0])})}catch(e){next(e)}});
app.post('/api/admin/users/:id/reactivate',auth,roles('admin'),async(req,res,next)=>{try{const r=await q("UPDATE users SET status='ACTIVE' WHERE id=$1 RETURNING *",[req.params.id]);if(!r.rowCount)return res.sendStatus(404);await audit('ADMIN_REACTIVATED_USER',req.user.id,{userId:req.params.id});res.json({user:cleanUser(r.rows[0])})}catch(e){next(e)}});
app.get('/api/admin/audit',auth,roles('admin'),async(req,res,next)=>{try{const r=await q('SELECT * FROM audit ORDER BY at DESC LIMIT 500');res.json({audit:r.rows})}catch(e){next(e)}});
app.get('/api/admin/settings',auth,roles('admin'),async(req,res,next)=>{try{const r=await q('SELECT key,value FROM settings');const settings=Object.fromEntries(r.rows.map(x=>[x.key,json(x.value)]));res.json({settings})}catch(e){next(e)}});
app.put('/api/admin/settings',auth,roles('admin'),async(req,res,next)=>{try{const allowed={commission:Number(req.body.commission),reviewWindowHours:Number(req.body.reviewWindowHours),autoApproveHours:Number(req.body.autoApproveHours)};if(!Number.isFinite(allowed.commission)||allowed.commission<0||allowed.commission>100||allowed.reviewWindowHours<1||allowed.autoApproveHours<1)return res.status(400).json({error:'Invalid settings'});for(const [k,v] of Object.entries(allowed))await q('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,JSON.stringify(v)]);await audit('ADMIN_UPDATED_SETTINGS',req.user.id,allowed);res.json({settings:allowed})}catch(e){next(e)}});
app.get('/api/admin/jobs',auth,roles('admin'),async(req,res,next)=>{try{const r=await q(`SELECT j.*,c.name client_name,t.name talent_name FROM jobs j JOIN users c ON c.id=j.client_id LEFT JOIN users t ON t.id=j.talent_id ORDER BY j.created_at DESC LIMIT 1000`);res.json({jobs:r.rows.map(x=>({...publicJob(x),clientName:x.client_name,talentName:x.talent_name}))})}catch(e){next(e)}});
app.get('/api/admin/payments',auth,roles('admin'),async(req,res,next)=>{try{const r=await q(`SELECT p.*,j.title job_title FROM payments p JOIN jobs j ON j.id=p.job_id ORDER BY p.created_at DESC LIMIT 1000`);res.json({payments:r.rows})}catch(e){next(e)}});
app.get('/api/admin/reviewer-applications',auth,roles('admin'),async(req,res,next)=>{try{const r=await q('SELECT a.*,u.name,u.email FROM reviewer_applications a JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC');res.json({applications:r.rows.map(x=>({...x,specialties:json(x.specialties,[]),portfolio:json(x.portfolio,[]),references:json(x.references_json,[])}))})}catch(e){next(e)}});
app.get('/api/reviewer/my-application',auth,async(req,res,next)=>{try{const r=await q('SELECT * FROM reviewer_applications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[req.user.id]);if(!r.rowCount)return res.json({application:null});const x=r.rows[0];res.json({application:{...x,specialties:json(x.specialties,[]),portfolio:json(x.portfolio,[]),references:json(x.references_json,[])}})}catch(e){next(e)}});
app.post('/api/admin/reviewer-applications/:id/decision',auth,roles('admin'),async(req,res,next)=>{try{const approved=Boolean(req.body.approved),r=await q("UPDATE reviewer_applications SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3 RETURNING *",[approved?'QUALIFICATION':'REJECTED',req.user.id,req.params.id]);if(!r.rowCount)return res.sendStatus(404);if(approved)await q("INSERT INTO reviewer_tests(application_id,user_id,status) VALUES($1,$2,'PENDING') ON CONFLICT(application_id) DO NOTHING",[r.rows[0].id,r.rows[0].user_id]);res.json(r.rows[0])}catch(e){next(e)}});
app.post('/api/admin/reviewers/:id/qualification',auth,roles('admin'),async(req,res,next)=>{try{const score=Number(req.body.score);if(!Number.isFinite(score)||score<0||score>100)return res.status(400).json({error:'Score must be 0-100'});const level=score>=90?'CERTIFIED':score>=75?'TRAINEE':'REJECTED';const role=level==='REJECTED'?'talent':'reviewer';const r=await q('UPDATE users SET reviewer_score=$1,reviewer_level=$2,role=$3 WHERE id=$4 RETURNING *',[score,level,role,req.params.id]);if(!r.rowCount)return res.sendStatus(404);await q("UPDATE reviewer_applications SET status=$1 WHERE user_id=$2 AND status='QUALIFICATION'",[level==='REJECTED'?'REJECTED':'APPROVED',req.params.id]);res.json({user:cleanUser(r.rows[0])})}catch(e){next(e)}});

async function autoApproveSweep(){try{const hours=Number(await setting('autoApproveHours',72));const r=await q("UPDATE jobs SET status='APPROVED',payment_status='RELEASE_PENDING',approved_at=now() WHERE status='CLIENT_REVIEW' AND submitted_at IS NOT NULL AND submitted_at <= now() - ($1::text || ' hours')::interval RETURNING id,title,talent_id,client_id",[String(hours)]);for(const j of r.rows){await audit('AUTO_APPROVED', 'SYSTEM',{jobId:j.id});if(j.talent_id)await notify(j.talent_id,'AUTO_APPROVED','Job auto-approved',`“${j.title}” passed the automatic review window and is ready for payout.`,{jobId:j.id})}}catch(e){console.error('auto approve sweep',e.message)}}
setInterval(autoApproveSweep,5*60*1000).unref();
/* ============================ SUPPORT CHAT ============================ */
const publicThread = t => ({ id:t.id, status:t.status, createdAt:t.created_at });
const publicSMsg = m => ({ id:m.id, senderType:m.sender_type, senderName:m.sender_name, body:m.body, createdAt:m.created_at });

app.post('/api/support/message',optionalAuth,async(req,res,next)=>{try{
  const body=String(req.body.body||'').trim().slice(0,3000);
  if(!body)return res.status(400).json({error:'Message cannot be empty'});
  let threadId=req.body.threadId?String(req.body.threadId):null;
  let thread=null;
  if(threadId){thread=(await q('SELECT * FROM support_threads WHERE id=$1',[threadId])).rows[0]||null;
    if(thread&&req.user&&thread.user_id&&thread.user_id!==req.user.id)thread=null;
    if(thread&&!req.user&&req.body.guestToken&&thread.guest_token!==String(req.body.guestToken))thread=null;
  }
  if(!thread&&req.user){thread=(await q("SELECT * FROM support_threads WHERE user_id=$1 AND status='OPEN' ORDER BY created_at DESC LIMIT 1",[req.user.id])).rows[0]||null;}
  if(!thread){
    const guestToken=req.user?null:String(req.body.guestToken||crypto.randomUUID());
    const name=req.user?req.user.name:String(req.body.name||'Guest').slice(0,100);
    const email=req.user?req.user.email:String(req.body.email||'').slice(0,200);
    thread=(await q('INSERT INTO support_threads(user_id,guest_token,guest_name,guest_email) VALUES($1,$2,$3,$4) RETURNING *',[req.user?req.user.id:null,guestToken,name,email])).rows[0];
  }
  const senderName=req.user?req.user.name:(thread.guest_name||'Guest');
  const m=(await q("INSERT INTO support_messages(thread_id,sender_type,sender_name,body) VALUES($1,'visitor',$2,$3) RETURNING *",[thread.id,senderName,body])).rows[0];
  const msgs=(await q('SELECT * FROM support_messages WHERE thread_id=$1 ORDER BY created_at',[thread.id])).rows;
  res.status(201).json({thread:publicThread(thread),guestToken:thread.guest_token,messages:msgs.map(publicSMsg)});
}catch(e){next(e)}});

app.get('/api/support/thread/:id',optionalAuth,async(req,res,next)=>{try{
  const thread=(await q('SELECT * FROM support_threads WHERE id=$1',[req.params.id])).rows[0];
  if(!thread)return res.sendStatus(404);
  const owns=(req.user&&thread.user_id===req.user.id)||(!req.user&&req.query.guestToken&&thread.guest_token===String(req.query.guestToken));
  if(!owns)return res.sendStatus(403);
  const msgs=(await q('SELECT * FROM support_messages WHERE thread_id=$1 ORDER BY created_at',[thread.id])).rows;
  res.json({thread:publicThread(thread),messages:msgs.map(publicSMsg)});
}catch(e){next(e)}});

app.get('/api/admin/support',auth,roles('admin'),async(req,res,next)=>{try{
  const r=await q(`SELECT t.*,u.name user_name,u.email user_email,
    (SELECT body FROM support_messages m WHERE m.thread_id=t.id ORDER BY created_at DESC LIMIT 1) last_body,
    (SELECT created_at FROM support_messages m WHERE m.thread_id=t.id ORDER BY created_at DESC LIMIT 1) last_at
    FROM support_threads t LEFT JOIN users u ON u.id=t.user_id ORDER BY last_at DESC NULLS LAST LIMIT 200`);
  res.json({threads:r.rows.map(t=>({id:t.id,status:t.status,name:t.user_name||t.guest_name,email:t.user_email||t.guest_email,lastBody:t.last_body,lastAt:t.last_at,createdAt:t.created_at}))});
}catch(e){next(e)}});

app.get('/api/admin/support/:id',auth,roles('admin'),async(req,res,next)=>{try{
  const thread=(await q('SELECT t.*,u.name user_name,u.email user_email FROM support_threads t LEFT JOIN users u ON u.id=t.user_id WHERE t.id=$1',[req.params.id])).rows[0];
  if(!thread)return res.sendStatus(404);
  const msgs=(await q('SELECT * FROM support_messages WHERE thread_id=$1 ORDER BY created_at',[thread.id])).rows;
  res.json({thread:{...publicThread(thread),name:thread.user_name||thread.guest_name,email:thread.user_email||thread.guest_email},messages:msgs.map(publicSMsg)});
}catch(e){next(e)}});

app.post('/api/admin/support/:id/reply',auth,roles('admin'),async(req,res,next)=>{try{
  const body=String(req.body.body||'').trim().slice(0,3000);
  if(!body)return res.status(400).json({error:'Message cannot be empty'});
  const thread=(await q('SELECT * FROM support_threads WHERE id=$1',[req.params.id])).rows[0];
  if(!thread)return res.sendStatus(404);
  await q("INSERT INTO support_messages(thread_id,sender_type,sender_name,body) VALUES($1,'admin',$2,$3)",[thread.id,req.user.name,body]);
  if(thread.user_id)await notify(thread.user_id,'SUPPORT_REPLY','New support reply','PRODILIVE support replied to your message.',{threadId:thread.id});
  const msgs=(await q('SELECT * FROM support_messages WHERE thread_id=$1 ORDER BY created_at',[thread.id])).rows;
  res.json({messages:msgs.map(publicSMsg)});
}catch(e){next(e)}});

app.post('/api/admin/support/:id/close',auth,roles('admin'),async(req,res,next)=>{try{
  const r=await q("UPDATE support_threads SET status='CLOSED' WHERE id=$1 RETURNING *",[req.params.id]);
  if(!r.rowCount)return res.sendStatus(404);
  res.json({thread:publicThread(r.rows[0])});
}catch(e){next(e)}});

app.get('/api/health',async(req,res)=>{let dbOk=true;try{await q('SELECT 1')}catch{dbOk=false}res.status(dbOk?200:503).json({ok:dbOk,service:'PRODILIVE Trust Engine',version:'5.0.0',database:dbOk,paystackConfigured:Boolean(process.env.PAYSTACK_SECRET_KEY),ffmpeg:true})});
app.use('/api',(req,res)=>res.status(404).json({error:'API route not found'}));
app.use((err,req,res,next)=>{console.error(err);if(err instanceof z.ZodError)return res.status(400).json({error:'Validation failed',details:err.issues.map(x=>x.message)});if(err.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'File too large'});if(err.code==='LIMIT_UNEXPECTED_FILE')return res.status(400).json({error:err.message||'Unsupported upload'});if(err.code==='23505')return res.status(409).json({error:'Resource already exists'});res.status(500).json({error:process.env.NODE_ENV==='production'?'Internal server error':err.message})});

if(process.env.NODE_ENV==='production'){const required=['DATABASE_URL','ADMIN_EMAIL','ADMIN_PASSWORD','PAYSTACK_SECRET_KEY','APP_URL'];const missing=required.filter(k=>!process.env[k]);if(missing.length){console.error('Missing required production environment variables:',missing.join(', '));process.exitCode=1;}}

ensureAdmin().catch(e=>console.error('Admin bootstrap:',e.message));
const server=createServer(app);
const io=new SocketIOServer(server,{cors:{origin:process.env.APP_URL||'*'}});
io.on('connection',()=>{});
server.listen(PORT,()=>console.log(`PRODILIVE running on ${PORT}`));
async function shutdown(){server.close(()=>pool.end().then(()=>process.exit(0)));setTimeout(()=>process.exit(1),10000)}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
